name: delete comments from open-collective-bot
on:
  issue_comment:
    types: [created]
jobs:
  delete-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: izhangzhihao/delete-comment@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: jumapeter
          issue_number: ${{ github.event.number }}  # remove comments from the current PR
